package com.abi.agro_back.collection;

public enum SellType {
    ROSLYNNYTSTVO,
        ZERNOVI,
        TEKHNICHNI,
        KORMOVI,
        OVOCHEVI,
        BASHTANNI,
        SADIVNYTSTVO,
        VYNOGRADARSTVO,
        KVITKARSTVO,
    TVARYNNYTSTVO,
        SKOTARSTVO,
        SVYNARSTVO,
        VIVCHARSTVO,
        PTAKHIVNYTSTVO,
//        RYBNYTSTVO,
        BJILNYTSTVO,
    HARCHOVA_PROMYSLOVIST,
        MYASO,
        RYBA,
        BOROSHNO,
        TSUKOR,
        MOLOKO,
        HLIB,
        MASLO,
        KONDYTERSKA,
        SPYRTOVA,
        MAKARONNA,
        PYVOVARNA,
        VYNOROBNA,
        KRUPY,
        KONSERVY,
        TUTUN,
    LIS_TA_VYROBY_Z_DEREVA,
    BUDIVELNA_GALUZ_I_REMONT,
    NAFTA_I_PALYVO,
    ZASOBY_ZAHYSTU,
    TRANSPORT,
    INSHA_TORGIVLYA,
    INSHA_SFERA,

}
